parameters:
  rstring.length: 5

services:
  _defaults:
    public: true

  rstring:
    class: src\Project\Service\String\Generator\RandomString
    arguments: ["@service_container"]


  converter.index:
    class: src\Project\Service\String\Converter\Index